name: meta_batida
description: "A Flutter project for image manipulation and sharing."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2 # Captura e seleção de imagens
  path_provider: ^2.1.5 # Acesso ao diretório temporário
  share_plus: ^10.1.3 # Compartilhamento de arquivos
  image: ^3.0.2 # Manipulação de imagens (resize, merge)
  cupertino_icons: ^1.0.8 # Ícones no estilo iOS
  pinch_zoom: ^2.0.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Adicione os caminhos dos assets necessários
  assets:
    - assets/self.jpg
    - assets/moldura_pub_geral.png
    - assets/medalha_jan.png
